version: '3.4'

services:
  flask:
    container_name: flaskblog
    #image: flaskblog
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - TLS=${TLS}
      - SSL=${SSL}
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - MAIL_SERVER=${MAIL_SERVER}
  
