#version: '3.4'

services:
  flask:
    container_name: flaskblog
    #image: flaskblog
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - TLS=${TLS}
      - SSL=${SSL}
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - MAIL_SERVER=${MAIL_SERVER}
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=flask_password
      - MYSQL_DATABASE=flaskdb
      - MYSQL_USER=flask_user
      - MYSQL_PASSWORD=flask_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
  
